apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cpt-demo
  name: cpt-demo
  namespace: cpt-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpt-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cpt-demo
    spec:
      containers:
        - image: kgopi1/cpt-demo:v1
          name: cpt-demo
          resources: {}
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV1
              valueFrom:
                configMapKeyRef:
                  name: cpt-demo-cm
                  key: ENV1
            - name: ENV2
              valueFrom:
                secretKeyRef:
                  name: cpt-demo-secret
                  key: ENV2

status: {}
