apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cpt-svc-np
  name: cpt-svc-np
  namespace: cpt-demo
spec:
  ports:
    - name: 5000-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: cpt-demo
  type: NodePort
status:
  loadBalancer: {}
