apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cpt-demo
  name: cpt-svc
  namespace: cpt-demo
spec:
  ports:
    - name: cpt-demo
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: cpt-demo
  type: ClusterIP
status:
  loadBalancer: {}
