apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.name}}-cm
  namespace: {{ .Release.namespace }}
  labels:
    app: {{.Values.name }}
    app.kubernetes.io/version: {{.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{.Release.Service }}
data:
  ENV1: {{ .Values.configmap.key1 }}
