apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name }}
    app.kubernetes.io/version: {{.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{.Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{.Values.name }}
  namespace: {{.Release.namespace }}
spec:
  replicas: {{.Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{.Values.name }}
  template:
    metadata:
      labels:
        app: {{.Values.name }}
    spec:
      containers:
        - image: {{ .Values.deploy.image }}
          name: {{ .Values.name }}
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENV1
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-cm
                  key: {{ .Values.configmap.key1 }}
            - name: ENV2
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: {{ .Values.secret.key1 }}
