apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.name }}
    app.kubernetes.io/version: {{.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{.Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{.Values.name }}
  namespace: {{.Release.namespace }}
spec:
  ports:
    - name: cpt-demo
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: {{.Values.name }}
  type: ClusterIP
